stages:          # List of stages for jobs, and their order of execution
  - test

unit-test-job:       # This job runs in the build stage, which runs first.
  image: python:3.12
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install .
    - pip install pytest
  script:
    - python -m pytest
  
